Wildlife_Conservation_Education_Initiative/Wildlife_Conservation_Education_Initiative/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('safari_learning/', include('safari_learning.urls', namespace="safari")),
    path("accounts/", include("django.contrib.auth.urls"))
]

Wildlife_Conservation_Education_Initiative/safari_learning/urls.py
from django.urls import path
from . import views

# Set the app name for namespacing
app_name = 'safari_learning'

# Define the URL patterns for the MonkTraderApp
urlpatterns = [
    # Path for the safari user signup page
    path("safari_user_signup/", views.safari_user_signup, name='signup'),
    # Path for the safari user login page
    path('safari_user_login/', views.safari_user_login, name='login'),
    # Path for homepage
    path("safari_user_homepage/", views.safari_user_homepage, name='homepage'),
    path("interests/<int:user_id>/", views.safari_user_interests, name='interests'),
    path("clickedinterest/<int:user_id>/", views.safari_user_clicked_interest, name='clickedinterest'),
    path("deleteinterest/<int:user_id>/", views.safari_user_delete_interest, name='deleteinterest'),
    path("error_view/", views.safari_error_view, name='error_view'),
    path("book_event/", views.BookEventView, name='book_event'),
    path("landing_page/", views.LandingView, name='landing_page'),
    path("faq_page/", views.FAQView, name='faq_page'),
]

Wildlife_Conservation_Education_Initiative/safari_learning/models.py
import os
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.conf import settings

# utility function for checking for the legal age, and real age
def validate_age(age):
    max_age = 150
    min_age = 10
    if age > max_age:
        raise ValidationError(
            _("Age %(age)s is above the maximum age of %(max_age)s required to register :("),
            params={"age": age, "max_age": max_age},
        )
    if age < min_age:
        raise ValidationError(
            _("Age %(age)s is below the minimum age of %(min_age)s required to register :("),
            params={"age": age, "min_age": min_age},
        )

def images_path():
    return os.path.join(settings.BASE_DIR, "safari_learning/static/course_image")
# Create your models here.



class SafariUser(AbstractUser):
    age = models.PositiveSmallIntegerField(validators=[validate_age], null=True)
    profession = models.CharField(max_length=200)
    interests = models.JSONField(null=True)

    def __str__(self):
        return "<{0}> {1} {2} {3} is registered".format(self.__class__.__name__, self.id, self.first_name, self.last_name)
    
class SafariCourse(models.Model):
    course_name = models.CharField(max_length=600, default="no course name")
    course_link = models.URLField(max_length=600)
    file_name = models.FilePathField(path=images_path, match=r'\.(jpg|jpeg|png|gif|bmp)$')
    profession_json = models.JSONField(null=True)
    course_tags = models.JSONField(null=True)

    def __str__(self):
        return "<{0}> image {1} is saved".format(self.__class__.__name__, self.file_name)
    
class Interest(models.Model):
    interest = models.CharField(max_length=700)

class Event(models.Model):
    EVENT_CHOICES = [
        ('Entrepreneurship and Ventures Masterclass', 'Entrepreneurship and Ventures Masterclass'),
        ('Wildlife Campaign Awareness', 'Wildlife Campaign Awareness'),
        ('Sustainable Futures Forum', 'Sustainable Futures Forum'),
        ('Wildlife Warriors Workshop', 'Wildlife Warriors Workshop'),
        ('Wildlife Conservation Symposium', 'Wildlife Conservation Symposium'),
        # add more events and login to the admin to create them.
    ]
    
    event_name = models.CharField(max_length=1000, choices=EVENT_CHOICES)
    date = models.DateField()
    location = models.CharField(max_length=1000)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.get_event_name_display()
    
class BookedEvent(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=False,
        related_name="user_events",
    )
    events = models.ForeignKey(
        Event,
        on_delete=models.PROTECT,
        related_name="all_booking",
        null=True,
    )

Wildlife_Conservation_Education_Initiative/safari_learning/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from .models import SafariUser
from django.forms import ModelForm
from .models import SafariUser, Event

# define the UserCreationForm  for the safari users to register with
class SafariUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = SafariUser
        fields = ("first_name", "last_name", "email") + UserCreationForm.Meta.fields + ("age", "profession")


"""
Define the Authentication Form for the safari users

This form authenticates with the backends provided by django settings
but it uses the user model set to the settings.AUTH_USER_MODEL
to do some validations which are;
The AuthenticationForm performs several internal validations:

1. Username Existence: It checks whether the provided username exists in the database.
2. Password Matching: It verifies if the provided password matches the stored hashed password for the given username. This is done using Django's authenticate function.

The AuthenticationForm provides two fields:

1. username
2. password
"""
class SafariUserAuthenticationForm(AuthenticationForm):
    pass

class SafariForm(ModelForm):
    class Meta:
        model = SafariUser
        fields = ["username", "email"]

class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = ["event_name"]

Wildlife_Conservation_Education_Initiative/safari_learning/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import SafariUserCreationForm, SafariUserAuthenticationForm, SafariForm, EventForm
from django.urls import reverse
from .models import SafariCourse, Interest, SafariUser, Event, BookedEvent
from django.http import JsonResponse
import json

# Create your views here.

def safari_user_signup(request):
    template_name = "safari_learning/safari_auth.html"
    context_variable = {}
    context_variable["animation"] = "animation"
    if request.method == "POST":
        safari_signup_form = SafariUserCreationForm(data=request.POST)
        if safari_signup_form.is_valid():
            """
            1. Save the form to the model and commit to database,
            2. Then get the cleaned up username, and password, then
            try to get the safari user object, by using the authenticate
            method to see if username exists, and if that password belongs to that username also
            3. Log the safari user in by using the login function i.e putting is_authenticated=True for that safariuser, and assigning the safariuser to the request.user property
            """
            safari_signup_form.save()
            username = safari_signup_form.cleaned_data.get("username")
            password = safari_signup_form.cleaned_data.get("password1")
            safari_user = authenticate(request, username=username, password=password)
            print(safari_user)
            if safari_user:
                login(request, safari_user)
                # TODO redirect user to view name
                print("sending user to homepage")
                return redirect("safari:landing_page")

            # if not send user to signup again since authenticate returned none
            context_variable["safari_signup_form"] = SafariUserCreationForm()
            return render(request, template_name, context_variable)
        
        context_variable["safari_signup_form"] = safari_signup_form
        context_variable["safari_form_errors"] = "An error occured when validating this signup form check page for errors made :("
        return render(request, template_name, context_variable)

    # for GET method
    safari_signup_form = SafariUserCreationForm()
    context_variable["safari_signup_form"] = safari_signup_form
    return render(request, template_name, context_variable)

def safari_user_login(request):
    template_name = "safari_learning/safari_auth.html"
    context_variable = {}
    context_variable["animation"] = "animation"
    if request.method == "POST":
        safari_login_form = SafariUserAuthenticationForm(request, data=request.POST)
        if safari_login_form.is_valid():
            # now get the user from the authentication form using .get_user() method
            # then log the user in, then after redirect to home page
            safari_user = safari_login_form.get_user()
            login(request, safari_user)
            # TODO redirect user to home page
            return redirect("safari:landing_page")
        
        # if form is not valid give a div hint on the signup or login errors based on the form object
        # sent 
        context_variable["safari_login_form"] = safari_login_form
        context_variable["safari_form_errors"] = "An error occurred when validating this login action username and password are case sensitive"
        return render(request, template_name, context_variable)
    
    # for GET method
    safari_login_form = SafariUserAuthenticationForm(request)
    context_variable["safari_login_form"] = safari_login_form
    return render(request, template_name, context_variable)

def safari_user_homepage(request):
    template_name = "safari_learning/safari_homepage.html"
    context_variable = {}
    if request.user.is_authenticated:
        # TODO show user the homepage
        # TODO also take the necessary data for that page
        # TODO image url, links, based on the profession of the users
        safari_user = request.user
        print(safari_user.profession)
        safari_courses = SafariCourse.objects.filter(
            profession_json__profession__icontains=safari_user.profession,
        ).all()
        print(safari_courses)
        context_variable["safari_user"] = safari_user
        context_variable["safari_courses"] = safari_courses
        return render(request, template_name, context_variable)
    redirectback_here_link = reverse("safari:login")
    return redirect(redirectback_here_link)

def safari_user_interests(request, user_id):
    template_name_1 = "safari_learning/interests.html"
    template_name_2 = "safari_learning/interesterror.html"
    context_variable = {}

    if request.user.is_authenticated:
        if request.method == "GET":
            if request.user.id != user_id:
                return render(request, template_name_2)
            # get the actual user interest and also get all interest
            user_interests = request.user.interests
            if user_interests:
                user_interests = user_interests.get("interests", [])
            else:
                user_interests = []
            all_interests = Interest.objects.all()
            all_courses = SafariCourse.objects.all()
            print(all_courses) 
            recommended_courses = [recommended_course for recommended_course in all_courses if set(user_interests).intersection(recommended_course.course_tags.get("course_tags"))]
            context_variable["recommended_courses"] = recommended_courses
            context_variable["user_interests"] = user_interests
            context_variable["all_interests"] = all_interests
            context_variable["logged_in_user"] = request.user
            return render(request, template_name_1, context_variable)
        
    redirectback_here_link = reverse("safari:login")
    return redirect(redirectback_here_link)

def safari_user_clicked_interest(request, user_id):
    template_name = "safari_learning/interests.html"
    context_variable = {}

    if request.user.is_authenticated:
        if request.method == "POST":
            if request.user.id != int(user_id):
                return JsonResponse({'status': 'error', 'message': reverse("safari_learning:error_view")}, status=403)
            # get the actual user interest and also get all interest
            try:
                # Read and parse the JSON data from the request body
                data = json.loads(request.body.decode('utf-8'))
                get_interest = data.get('interest').strip()
                """
                before you return the response save this interest to
                the user authenticated interest json
                """
                get_user = SafariUser.objects.filter(
                    id=user_id
                ).first()

                if not get_user.interests:
                    interest_list = []
                    interest_list.append(get_interest)
                    interest_dict = {"interests": interest_list}
                    request.user.interests = interest_dict
                    request.user.save()
                else:
                    interest_dict = request.user.interests
                    print(interest_dict)
                    interest_dict.get("interests").append(get_interest)
                    print(interest_dict)
                    request.user.interests = interest_dict
                    request.user.save()
                
                response_data = {
                    "status": "OK",
                    "code": 200,
                    "data": get_interest,
                    "statusText": "success",
                }
                return JsonResponse(response_data)
            except json.JSONDecodeError:
                return JsonResponse({'status': 'error', 'message': 'Invalid JSON'}, status=400)
            except Exception as e:
                return JsonResponse({'status': 'error', 'message': str(e)}, status=500)
            
        if request.method == "GET":
            # get the actual user interest and also get all interest
            user_interests = request.user.interests
            if user_interests:
                user_interests = user_interests.get("interests", [])
            
            all_interests = Interest.objects.all()
            all_courses = SafariCourse.objects.all()
            recommended_courses = [recommended_course for recommended_course in all_courses if set(user_interests).intersection(recommended_course.course_tags.get("course_tags"))]
            context_variable["recommended_courses"] = recommended_courses
            context_variable["user_interests"] = user_interests
            context_variable["all_interests"] = all_interests
            context_variable["logged_in_user"] = request.user
            return render(request, template_name, context_variable)

        
    redirectback_here_link = reverse("safari:login")
    return redirect(redirectback_here_link)

def safari_user_delete_interest(request, user_id):
    template_name = "safari_learning/interests.html"
    context_variable = {}

    if request.user.is_authenticated:
        if request.method == "DELETE":
            if request.user.id != int(user_id):
                return JsonResponse({'status': 'error', 'message': reverse("safari_learning:error_view")}, status=403)
            # get the actual user interest and also get all interest
            try:
                # Read and parse the JSON data from the request body
                data = json.loads(request.body.decode('utf-8'))
                get_interest = data.get('interest').strip()
                """
                before you return the response save this interest to

Wildlife_Conservation_Education_Initiative/safari_learning/templates/safari_learning/interests.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://kit.fontawesome.com/95cc5340fb.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static './styles/Interests.css' %}" />
    <title>Interest Update</title>
  </head>
  <body>
    <header>
      <h1>Welcome to Safari {{ logged_in_user.first_name }} Portal</h1>
    </header>
    <nav>
      <a href="{% url 'safari:homepage' %}">Courses</a>
      <a href="{% url 'safari:interests' user.id %}">Interests</a>
      <a href="{% url 'safari:book_event' %}">Book Event</a>
      <a href="{% url 'safari:faq_page' %}">FAQ</a>
      <a href="{% url 'safari:landing_page' %}">Landing1 Page</a>
    </nav>
    {% if all_interests %}
      <main style="padding: 20px;">
        {% if user_interests %}
          <div class="interest-container">
            {% for each_interest_obj in all_interests %}
              {% if each_interest_obj.interest in user_interests %}
                <div id="div_user_interest_{{ forloop.counter }}" class="interest-item user-interest">
                  <span onclick="postRequest(event)" id="user_interest_{{ forloop.counter }}" class="interest-span user-interest-span">{{ each_interest_obj.interest }}</span>
                  <i class="fa-solid fa-circle-xmark remove-icon" id="{{ forloop.counter }}" onclick="deleteRequest(event)"></i>
                </div>
              {% else %}
                <div id="div_user_interest_{{ forloop.counter }}" class="interest-item">
                  <span onclick="postRequest(event)" id="user_interest_{{ forloop.counter }}" class="interest-span">{{ each_interest_obj.interest }}</span>
                </div>
              {% endif %}
            {% endfor %}
          </div>
        {% else %}
          <div class="interest-container">
            {% for each_interest_obj in all_interests %}
              <div id="div_user_interest_{{ forloop.counter }}" class="interest-item">
                <span onclick="postRequest(event)" id="user_interest_{{ forloop.counter }}" class="interest-span">{{ each_interest_obj.interest }}</span>
              </div>
            {% endfor %}
          </div>
        {% endif %}
        <br />
        {% comment %}Start carousel{% endcomment %}

        <div id="slideshow">
          <div class="slide-wrapper">
            {% for recommended_course in recommended_courses %}
              <div class="slide">
                <div class="course-div">
                  <div>
                    <img style="max-width: 100%; width: 100px; height: 100px;" src="{% static 'course_image/' %}{{ recommended_course.file_name }}" alt="{{ recommended_course.file_name }} pic" />
                  </div>
                  <div>{{ recommended_course.course_name }}</div>
                  <div>
                    <a href="{{ recommended_course.course_link }}" target="_blank">Course {{ forloop.counter }}</a>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>

        {% comment %}end carousel{% endcomment %}
      </main>
    {% else %}
      <div>No course tags filters yet</div>
    {% endif %}

    <footer>
      <p>&copy; 2024 Safari User Portal. All rights reserved.</p>
    </footer>
  </body>
  <script>
    const csrfTokenCookieValue = document.cookie
      .split('; ')
      .find((row) => row.startsWith('csrftoken='))
      ?.split('=')[1]
    
    const deleteRequest = (event) => {
      // get the i element, then extract it's id
      const iElement = event.currentTarget
      const iElementId = iElement.id
      // use this id to get the div(parenet element), and span(sibling)
      const spanElement = document.querySelector(`#user_interest_${iElementId}`)
      // remove the iElement from the divElement
      const removedIElement = iElement.parentNode.removeChild(iElement)
      // add the background color and color to the span element
      spanElement.style.backgroundColor = '#f53b3b'
      spanElement.style.color = '#000'
    
      const interestValue = spanElement.textContent
      const deleteInterest = async () => {
        try {
          const DELETEURL = '/safari_learning/deleteinterest/{{logged_in_user.id}}/'
          const response = await fetch(DELETEURL, {
            method: 'DELETE',
            headers: {
              'X-CSRFToken': csrfTokenCookieValue,
              'Content-Type': 'application/json'
            },
            body: JSON.stringify({ interest: interestValue })
          })
          if (!response.ok) {
            const data = await response.json()
            throw new Error(data.message)
          }
          const data = await response.json()
          console.log(data)
        } catch (error) {
          window.location.href = error.message
        }
      }
      deleteInterest()
    }
    
    const postRequest = (event) => {
      const domElement = event.currentTarget
      // when you change the color to greeen color variant already
      if (domElement.style.backgroundColor === 'rgb(108, 245, 108)') {
        console.log('quitting function early!!!')
        return
      }
      // change the background color
      domElement.style.backgroundColor = '#6cf56c'
      domElement.style.color = '#fff'
    
      // now get the span id
      const domElementId = domElement.id.split('_')[2]
      // now get the div that this spam element is in
      const domElementDiv = document.querySelector(`#div_user_interest_${domElementId}`)
      // now create the i element put the necessary class, id, and onclick attribute
      const iElement = document.createElement('i')
      iElement.className = 'fa-solid fa-circle-xmark'
      iElement.id = domElementId
      iElement.style.fontSize = '25px'
      iElement.setAttribute('onclick', 'deleteRequest(event)')
      domElementDiv.appendChild(iElement)
    
      const interestValue = domElement.textContent.trim()
      const postInterest = async () => {
        try {
          const POSTURL = '/safari_learning/clickedinterest/{{logged_in_user.id}}/'
          const response = await fetch(POSTURL, {
            method: 'POST',
            headers: {
              'X-CSRFToken': csrfTokenCookieValue,
              'Content-Type': 'application/json'
            },
            body: JSON.stringify({ interest: interestValue })
          })
          if (!response.ok) {
            const data = await response.json()
            throw new Error(data.message)
          }
          const data = await response.json()
          console.log(data)
        } catch (error) {
          window.location.href = error.message
        }
      }
      postInterest()
    }
  </script>
</html>

Wildlife_Conservation_Education_Initiative/safari_learning/templates/safari_learning/safari_auth.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!--     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        crossorigin="anonymous" referrerpolicy="no-referrer" />     -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'styles/safari_auth.css' %}" />
    <title>Safari Learning</title>
  </head>

  <body>
    <div class="container">
      <div>
        {% if safari_form_errors %}
          {% if safari_signup_form.errors %}
            <div>
              <p class="safari-signup">{{ safari_form_errors }}</p>
              <!-- Hovering the p tag displays the div with an hint message -->
              <div class="safari-signup signup-error-div"></div>
            </div>
          {% elif safari_login_form.errors %}
            <div>
              <p class="safari-login">{{ safari_form_errors }}</p>
              <!-- Hovering the p tag displays the div with an hint message -->
              <div class="safari-login login-error-div"></div>
            </div>
          {% endif %}
        {% endif %}
      </div>
      <div class="auth_div">
        <div class="auth_child_div {% if safari_login_form %} auth_active {% endif %}">
          <a href="{% url 'safari:login' %}" class="login-event">Login</a>
        </div>

        <div class="auth_child_div {% if safari_signup_form %} auth_active {% endif %}">
          <a href="{% url 'safari:signup' %}" class="signup-event">Signup</a>
        </div>
      </div>
      <form method="POST">
        {% csrf_token %}
        <div>
          {% if safari_signup_form %}
            <section id="sign-up-container">
              <div class="form-group signup">{{ safari_signup_form.first_name.label_tag }}
                {{ safari_signup_form.first_name }}</div>
              <div class="form-group signup">{{ safari_signup_form.last_name.label_tag }}
                {{ safari_signup_form.last_name }}</div>
              <div class="form-group signup">
                {{ safari_signup_form.username.label_tag }}
                {{ safari_signup_form.username }}
                {% if safari_signup_form.errors %}
                  <p>{{ safari_signup_form.errors.username }}</p>
                {% endif %}
              </div>
              <div class="form-group signup">
                {{ safari_signup_form.email.label_tag }}
                {{ safari_signup_form.email }}
                {% if safari_signup_form.errors %}
                  <p>{{ safari_signup_form.errors.email }}</p>
                {% endif %}
              </div>

              <div class="form-group signup">
                {{ safari_signup_form.age.label_tag }}
                {{ safari_signup_form.age }}
                {% if safari_signup_form.errors %}
                  <p>{{ safari_signup_form.errors.age }}</p>
                {% endif %}
              </div>
              <div class="form-group signup">{{ safari_signup_form.profession.label_tag }}
                {{ safari_signup_form.profession }}</div>

              <div class="form-group signup">{{ safari_signup_form.password1.label_tag }}
                {{ safari_signup_form.password1 }}</div>
              <div class="form-group signup">
                {{ safari_signup_form.password2.label_tag }}
                {{ safari_signup_form.password2 }}
                {% if safari_signup_form.errors %}
                  <p>{{ safari_signup_form.errors.password2 }}</p>
                {% endif %}
              </div>
            </section>
          {% endif %}
          <!-- Separating safari signup from safari login -->
          {% if safari_login_form %}
            <section id="login-container">
              <div class="form-group login">{{ safari_login_form.username.label_tag }}
                {{ safari_login_form.username }}</div>
              <div class="form-group login">{{ safari_login_form.password.label_tag }}
                {{ safari_login_form.password }}</div>
            </section>
          {% endif %}
        </div>
        <div class="form-group" style="margin-top: 20px;">
          <button type="submit" class="submit">
            {% if safari_signup_form %}
              Sign Up
            {% else %}
              Login
            {% endif %}
          </button>
        </div>
      </form>
    </div>
  </body>
  <script src="{% static 'scripts/safari_auth.js' %}"></script>
</html>

Wildlife_Conservation_Education_Initiative/safari_learning/templates/safari_learning/safari_homepage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static './styles/safari_homepage.css' %}" />
    <title>Safari Homepage</title>


  </head>
  <body>
    <header>
      <h1>Welcome to Safari {{safari_user.first_name}}</h1>
    </header>
    <nav>
      <a href="{% url 'safari:homepage' %}">Courses</a>
      <a href="{% url 'safari:interests' user.id %}">Interests</a>
      <a href="{% url 'safari:book_event' %}">Book Event</a>
      <a href="{% url 'safari:faq_page' %}">FAQ</a>
      <a href="{% url 'logout' %}">Log out</a>
      <a href="{% url 'safari:landing_page' %}">Landing Page</a>
    </nav>

    <main class="container">
      <section class="courses">
        {% for safari_course in safari_courses %}
          <article class="course-div">
            <img style="max-width: 100%; width: 100px; height: 100px;" src="{% static 'course_image/' %}{{ safari_course.file_name }}" alt="{{ safari_course.file_name }} pic" />
            <div class="info">
              <p>{{ safari_course.course_name }}</p>
              <a href="{{ safari_course.course_link }}" target="_blank">View Course {{ forloop.counter }}</a>
            </div>
          </article>
        {% endfor %}
      </section>
    </main>

    <footer>
      <p>&copy; 2024 Safari User Portal. All rights reserved.</p>
    </footer>
  </body>
</html>

Wildlife_Conservation_Education_Initiative/safari_learning/templates/safari_learning/safari_landingpage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Safari User Landing Page</title>
    <link rel="stylesheet" href="{% static 'styles/Landingpage.css' %}">
  </head>
  <body>
    <header>
      <h1>Welcome to Safari {{logged_in_user.first_name}} Portal</h1>
    </header>
    <nav>
      <a href="{% url 'safari:homepage' %}">Courses</a>
      <a href="{% url 'safari:interests' user.id %}">Interests</a>
      <a href="{% url 'safari:book_event' %}">Book Event</a>
      <a href="{% url 'safari:faq_page' %}">FAQ</a>
      <a href="{% url 'logout' %}">Log out</a>
    </nav>
<main>
    <div class="container">
      <div class="user-info">
        <h2>Hello, {{ logged_in_user.first_name }} {{ logged_in_user.last_name }}</h2>
        <p>Age: {{ logged_in_user.age }}</p>
        <p>Profession: {{ logged_in_user.profession }}</p>
        <div class="interests">
          {% for interest in logged_in_user.interests.interests %}
            <div class="interest">{{ interest }}</div>
          {% endfor %}
        </div>
      </div>
    </div>
  </main>
    <footer>
      <p>&copy; 2024 Safari User Portal. All rights reserved.</p>
    </footer>
  </body>
</html>